services:

  postgres:
    container_name: postgres
    image: postgres:14.2
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - app-postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - app-redis:/var/lib/redis/data

  app:
    container_name: rails
    build:
      context: .
    volumes:
      - ./app:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env

  sidekiq:
    container_name: sidekiq
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - app
    ports:
      - '8020:8020'

volumes:
  app-postgres:
  app-redis: